### ISSUE TITLE
CÙNG Ý TƯỞNG VỚI MÌNH NHA

### ISSUE THREAD

**Issue by minhtanz1** [Dangduytoan12l/WordToExcel#16]
Thì hiện tại, mình cũng có repo giống ý tưởng của bạn, nhưng mình vẫn còn lỗi đó là các kí tự toán học, và phải clean dữ liệu (mấy cái râu ria) mới có thể chạy ổn. Dự án mình có thể chạy toán các môn KHXH có đánh đáp án (bold, underline, italic). Không biết mình và bạn có thể hợp tác với nhau không. :+)
Thanks
link: [https://github.com/PhamMinhTan1122/quiz-converter](url)
_do lười quá hầu hết các chức năng mới mình chưa push lên git có gì mình gửi dự án ổn định nhất nếu bạn cần_

**Comment by caphefalumi** [comment]
Các kí tự toán học như π, Ω trong mục symbol mình xử lý bình thường, chỉ có phương trình toán học cần phải thao tác lọc dữ liệu trên xml của file word, bạn gửi mình file ổn định coi thử

**Comment by minhtanz1** [comment]
kết bạn với zalo của mình nha: 
![image](https://github.com/caphefalumi/WordToExcel/assets/85481444/7224d6ce-47bf-4b25-98ab-0550534cd1a7)

**Comment by caphefalumi** [comment]
Bạn tham khảo thử branch dev của mình, hiện tại mình đã hoàn tất gui, tự động xuất file, nhận dạng câu trả lời, câu hỏi, lựa chọn
